name: deploy-website

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.0.0
      - name: install deps
        run: npm install
      - name: build app
        run: npm run docs:build
      - name: copy dist file with scp
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          pass: ${{secrets.REMOTE_PASS}}
          port: 22
          local: "./docs/dist"
          target: ${{secrets.REMOTE_TARGET}}
