name: deploy-website

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.0.0
      - name: install deps
        run: npm install
      # - name: get auth
      #   run: git update-index --chmod=+x script.sh
      - name: build app
        run: sudo npm run docs:build
      - name: copy dist file with scp
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASS}}
          port: 22
          connect_timeout: 10s
          local: "./docs/.vitepress/dist"
          remote: /home/github-action
