name: deploy-website

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.0.0
      - name: install deps
        run: npm install
      - name: build app
        run: npm run docs:build
      - name: copy dist file with scp
        uses: cross-the-world/scp-pipeline@v1.2.1
        with:
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          pass: ${{secrets.REMOTE_PASS}}
          port: 22
          connect_timeout: 10s
          local: "./docs/dist"
          remote: /home/github-action
